# Generated by Django 5.1.6 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='last_available_frame',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
