# Generated by Django 5.1.6 on 2025-04-04 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0002_stream_last_available_frame'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='last_available_frame',
        ),
    ]
