# Generated by Django 5.1.6 on 2025-04-04 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0003_remove_stream_last_available_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='last_frame_parsed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 4, 17, 31, 20, 150186)),
            preserve_default=False,
        ),
    ]
