# Generated by Django 5.1.6 on 2025-04-04 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0004_stream_last_frame_parsed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='last_frame_parsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
