# Generated by Django 5.1.6 on 2025-04-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0005_alter_stream_last_frame_parsed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsubscription',
            name='last_frame_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
