# Generated by Django 5.1.6 on 2025-04-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0006_streamsubscription_last_frame_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsubscription',
            name='target_bird_species',
            field=models.TextField(blank=True, help_text='JSON list of target bird species names to detect', null=True),
        ),
    ]
