# Generated by Django 5.1.6 on 2025-04-07 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0006_streamsubscription_last_frame_fetched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sns_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='streamsubscription',
            name='provide_notification',
            field=models.BooleanField(default=True),
        ),
    ]
