# Generated by Django 5.1.6 on 2025-04-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0007_streamsubscription_target_bird_species'),
        ('stream_handler', '0007_user_is_sns_subscribed_and_more'),
    ]

    operations = [
    ]
