# Generated by Django 5.1.6 on 2025-04-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0008_merge_20250412_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamsubscription',
            name='stream',
        ),
        migrations.AddField(
            model_name='streamsubscription',
            name='url',
            field=models.URLField(default='https://www.youtube.com/watch?v=56WBs0A4Kng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamsubscription',
            name='provide_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
    ]
