# Generated by Django 5.1.6 on 2025-04-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0009_remove_streamsubscription_stream_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='recognitionentry',
            table='recognition_entry',
        ),
        migrations.AlterModelTable(
            name='streamsubscription',
            table='stream_subscription',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
