# Generated by Django 5.1.6 on 2025-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0010_alter_recognitionentry_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsubscription',
            name='misc_info',
            field=models.TextField(blank=True, help_text='Can be used for messages from stream parsing backend', null=True),
        ),
    ]
