# Generated by Django 5.1.6 on 2025-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0011_streamsubscription_misc_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamsubscription',
            name='provide_notification',
            field=models.BooleanField(default=True),
        ),
    ]
