# Generated by Django 5.1.6 on 2025-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_handler', '0013_user_sns_topic_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamsubscription',
            name='target_timestamp_ms',
            field=models.IntegerField(default=1),
        ),
    ]
